version: '2'
services:
    efwservice-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/efwservice/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=efwservice
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
