version: '2'
services:
  efwgateway-app:
    image: efwgateway
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005
      - 'SPRING_PROFILES_ACTIVE=prod,webpack,zipkin,swagger,IDE'
      - 'EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka'
      - 'SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config'
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://efwgateway-postgresql:5432/efwgateway'
      - JHIPSTER_SLEEP=30
      - 'SPRING_DATA_JEST_URI=http://efwgateway-elasticsearch:9200'
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_ZK_NODES=zookeeper
      - JHIPSTER_REGISTRY_PASSWORD=admin
    ports:
      - '8080:8080'
      - '5005:5005'
  efwgateway-postgresql:
    image: 'postgres:10.4'
    environment:
      - POSTGRES_USER=efwgateway
      - POSTGRES_PASSWORD=
  efwgateway-elasticsearch:
    image: 'elasticsearch:5.6.13'
    command: '-Enetwork.host=0.0.0.0 -Ediscovery.type=single-node'
    environment:
      - ES_JAVA_OPTS=-Xms1024m -Xmx1024m

  efwservice-app:
    image: efwservice
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005
      - 'SPRING_PROFILES_ACTIVE=prod,webpack,zipkin,swagger,IDE'
      - 'EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka'
      - 'SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config'
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://efwservice-postgresql:5432/efwservice'
      - JHIPSTER_SLEEP=30
      - 'SPRING_DATA_JEST_URI=http://efwservice-elasticsearch:9200'
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_ZK_NODES=zookeeper
      - JHIPSTER_REGISTRY_PASSWORD=admin
    ports:
      - '8081:8081'
      - '5006:5005'
  efwservice-postgresql:
    image: 'postgres:10.4'
    environment:
      - POSTGRES_USER=efwservice
      - POSTGRES_PASSWORD=
  efwservice-elasticsearch:
    image: 'elasticsearch:5.6.13'
    command: '-Enetwork.host=0.0.0.0 -Ediscovery.type=single-node'
    environment:
      - ES_JAVA_OPTS=-Xms1024m -Xmx1024m

  zookeeper:
    extends:
      file: kafka.yml
      service: zookeeper
  kafka:
    extends:
      file: kafka.yml
      service: kafka
  jhipster-registry:
    extends:
      file: jhipster-registry.yml
      service: jhipster-registry

  jhipster-elasticsearch:
    extends:
      file: jhipster-console.yml
      service: jhipster-elasticsearch
  jhipster-logstash:
    extends:
      file: jhipster-console.yml
      service: jhipster-logstash
    depends_on:
      - jhipster-elasticsearch
  jhipster-console:
    extends:
      file: jhipster-console.yml
      service: jhipster-console
    depends_on:
      - jhipster-elasticsearch
  jhipster-import-dashboards:
    extends:
      file: jhipster-console.yml
      service: jhipster-import-dashboards
    depends_on:
      - jhipster-elasticsearch
  jhipster-curator:
    extends:
      file: jhipster-console.yml
      service: jhipster-curator
    depends_on:
      - jhipster-elasticsearch
  jhipster-zipkin:
    extends:
      file: jhipster-console.yml
      service: jhipster-zipkin
    depends_on:
      - jhipster-elasticsearch
